name 'hw_cookbooks_graphiti'
maintainer       'Heavy Water Software Inc.'
maintainer_email 'ops@hw-ops.com'
license          'Apache-2.0'
description      'Installs/Configures graphiti'
version          '0.1.2'
depends 'ruby_installer'
depends 'runit'
